language: java
jdk:
  - openjdk11  # You can use openjdk8 or another version if needed

addons:
  sonarcloud:
    organization: "tsundgerhen"
    token:
       secure: "R0fchZ81OHjRZm7eH6wXEhcCbTok1J6GHUtZBvpH6OQxwQaSl1qV4JPxauIw7yW8zCERylHvgBht8Sth0zkrZsO/j5oHVnr/QxFFxOOArAtvgi5yMnZ/HmOSGtkKUIacRcvJsBS2H61ERi80x6EuaYEgnlVsY4nyPxf/soI4iqJpof33h3f+UBJcdQpwi92g1Yudq6BifjoW6HyENqkt1tdc5Dnr/NmpJy8PONi4aDUizGREhJ9creWlAtVN6YaGHYP0gs8eyRh+GdHOGjZq2NkF0a3chi/6TsTK+6GeBh41iVvlMvLYDzNF0sJZw2Zp1tNL92pi7EjOgdHN2v3GY5Xsg2XfzaVkkrIDHenAK8uqj2eWsvftS0kEOAHUxq71anLRQCOSPXWucFG434zesVGrOzWjH8V2dVHIw1Vr8s/4Q5AZEchuCxvBP0Opsrt6M/CpfiC3lfJ09u2E+PNEKm2vwlNV+cRF3kIxYbnU4EPGPEoQ4jnmszN5TPdc2+pC4zjg+4PIgY6FNHSEIBgi8C11SA1e1vnOCUrPM5HSCM6EncHiL0gETlujmn1rWrHMkJ+BE4qUxsiBLK3SFCzVGliDlE9PzMwIOBzN+m2Hq55pKN4nCR7fJE629qAZOWPe9yc5UfC0pAXo6n1hLlXCWnWIATyY6uGhw2XUN2SQ8I4="

script:
  - ./gradlew clean build  # Or `mvn clean install` if you're using Maven
  - ./gradlew sonar  # This will trigger the SonarCloud analysis after the build

 